server.port=8083
#spring.jpa.hibernate.ddl-auto=none
#spring.jpa.hibernate.ddl-auto=create
spring.jpa.hibernate.ddl-auto=update
#spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.show_sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.enable_lazy_load_no_trans=true
spring.jpa.hibernate.naming.physical-strategy=org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl

spring.profiles.active=dev

#mail
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=satan22072005@gmail.com
# mkud
spring.mail.password=${mkud}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

#gg drive
google.drive.folder.ekyc.id=1yO7nbMJFIDMUCWh-PsjtSHy7fz4Dsz_V
google.drive.folder.report.id=1kDRmTmO-D46wR6bra9Mx6D-D5LTPkYTd
google.drive.folder.chat.id=1T9lIHOjRYyCS2-siZvmQXLYNRLuIsyPR

# Cau hinh OAuth 2.0
google.drive.client.id=${google_client_id}
google.drive.client.secret=${google_client_secret}
google.drive.refresh.token=${google_refresh_token}
#redis
spring.data.redis.host=localhost
spring.data.redis.port=6379

# Upload multipart limit
spring.servlet.multipart.max-file-size=50MB
spring.servlet.multipart.max-request-size=100MB